version: '3'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/formula
      - public-data:/formula/public
      - tmp-data:/formula/tmp
      - log-data:/formula/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/formula/public
      - tmp-data:/formula/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  mysql-data:
    driver: local
  public-data:
  tmp-data:
  log-data: