version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          - BUNDLER_VERSION: 2.1.4
          - RAILS_ENV: 'test'
    # executor: ruby/default
      - image: circleci/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_DATABASE: docker_test
    
    working_directory: ~/formula

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # - run: mv config/database.yml.ci config/database.yml

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load


      - run: echo "hello world"
          # name: Which bundler?
          # command: gem install bundler:2.1.4
      # - ruby/bundle-install
