default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: docker_development

test:
  <<: *default
  username: 'test_user'
  password: 'password'
  host: '127.0.0.1'
  database: docker_test

production:
  <<: *default
  database: formula_production
  username: formula
  password: <%= ENV['FORMULA_DATABASE_PASSWORD'] %>