default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password:
  # socket: /tmp/mysql.sock
  # username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  # password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  # host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: docker_development

test:
  <<: *default
  username: 'test_user'
  password: 'password'
  host: '127.0.0.1'
  database: docker_test

production:
  <<: *default
  # Mariadbの接続先
  # database: formula_production
  # username: root
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # socket: /var/lib/mysql/mysql.sock

  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: 'admin'
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: '3306'